// Central registry for the cinematic environment sequences currently used by the portfolio.
// Project/case-study data is intentionally empty until real, verified work is curated.

const worlds = [
  {
    id: 0,
    slug: 'world-02',
    name: 'Environment I',
    chapter: 'Environment Design',
    title: 'Worlds That\nFeel Real',
    subtitle: 'Unreal Engine 5 · Lighting · Environment Art',
    accentColor: '#7c5cc4',
    accentRGB: [124, 92, 196],
    framesPath: 'https://pub-88341f47988743aba3154d2af5c6327e.r2.dev/world-02/',
    frameCount: 165,
    sourcePattern: 'WAY.Layer1.%04d.jpeg',
    sourceStart: 0,
    ambientAudio: 'assets/audio/world-02-ambient.ogg',
    projects: [],
  },
  {
    id: 1,
    slug: 'world-01',
    name: 'Environment II',
    chapter: 'World Building',
    title: 'Built For\nThe Frame',
    subtitle: 'Unreal Engine 5 · Blender · Substance 3D',
    accentColor: '#c46428',
    accentRGB: [196, 100, 40],
    framesPath: 'https://pub-88341f47988743aba3154d2af5c6327e.r2.dev/world-01/',
    frameCount: 111,
    sourcePattern: 'NewLevelSequence.Layer1.%04d.jpeg',
    sourceStart: 1,
    ambientAudio: 'assets/audio/world-01-ambient.ogg',
    projects: [],
  },
  {
    id: 2,
    slug: 'world-03',
    name: 'Cinematic I',
    chapter: 'Cinematic Rendering',
    title: 'Every Frame\nComposed',
    subtitle: 'Blender · Unreal Engine 5 · DaVinci Resolve',
    accentColor: '#3a8c52',
    accentRGB: [58, 140, 82],
    framesPath: 'https://pub-88341f47988743aba3154d2af5c6327e.r2.dev/world-03/',
    frameCount: 124,
    sourcePattern: 'NewLevel.%04d.jpeg',
    sourceStart: 0,
    ambientAudio: 'assets/audio/world-03-ambient.ogg',
    projects: [],
  },
  {
    id: 3,
    slug: 'world-04',
    name: 'Cinematic II',
    chapter: 'VFX & Motion',
    title: 'Motion With\nPurpose',
    subtitle: 'After Effects · VFX · Motion Design',
    accentColor: '#2872c4',
    accentRGB: [40, 114, 196],
    framesPath: 'https://pub-88341f47988743aba3154d2af5c6327e.r2.dev/world-04/',
    frameCount: 179,
    sourcePattern: 'NewlSequence.Layer1.%04d.jpeg',
    sourceStart: 4,
    ambientAudio: 'assets/audio/world-04-ambient.ogg',
    projects: [],
  },
  {
    id: 4,
    slug: 'world-05',
    name: 'Atmosphere',
    chapter: 'Lighting & Atmosphere',
    title: 'Light That\nTells Stories',
    subtitle: 'Unreal Engine 5 · Lighting · Compositing',
    accentColor: '#c4a028',
    accentRGB: [196, 160, 40],
    framesPath: 'https://pub-88341f47988743aba3154d2af5c6327e.r2.dev/world-05/',
    frameCount: 375,
    sourcePattern: 'NewLevelSequence1.Layer1.%04d.jpeg',
    sourceStart: 0,
    ambientAudio: 'assets/audio/world-05-ambient.ogg',
    projects: [],
  },
];

export default worlds;
